spring:
  profiles:
    active: local-shiro
#  redis:
#    host:
#    database:
#    password:
#    timeout:

# Just test
#server:
#  port: 8080
#  servlet:
#    session:
#      tracking-modes: cookie
#      cookie:
#        http-only: true