spring:
  profiles:
    active: local-aop-log
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:aop_log
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath*:sql/table.sql
  h2:
    console:
      enabled: true