SELECT A.ID,
       A.USERNAME,
       A.PASSWORD,
       A.ENABLED,
       C.NAME    R_NAME,
       C.ENABLED R_ENABLED,
       E.NAME    P_NAME,
       E.ENABLED P_ENABLED
FROM SYS_USER A
         LEFT JOIN SYS_USER_ROLE B ON A.ID = B.UID
         LEFT JOIN SYS_ROLE C ON B.ROLE_NAME = C.NAME AND C.ENABLED = TRUE
         LEFT JOIN SYS_ROLE_PERMISSION D ON C.NAME = D.ROLE_NAME
         LEFT JOIN SYS_PERMISSION E ON D.PERMISSION_NAME = E.NAME AND E.ENABLED = TRUE
WHERE A.USERNAME = 'admin'
